app/assets/images/heli_admin/config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /vi/ do
    root "static_pages#home"
    
    resources :types
    resources :san_phams
    resources :tin_tucs
    devise_for :users, :skip => [:sessions]
      as :user do
      get 'admin/login' => 'devise/sessions#new', :as => :new_user_session
      post 'admin/login' => 'devise/sessions#create', :as => :user_session
      match 'admin/signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    end
  end

end

app/assets/images/heli_admin/app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end
  # GET /types/1
  # GET /types/1.json
  def show
    @type_childs = Type.where(:parent => @type.id)
    @type_child_ids = [@type.id]
    @type_childs.each do |type_child|
      @type_child_ids.push(type_child.id)
    end
    @san_phams = SanPham.where(:type_id => @type_child_ids).order('type_id asc').paginate(:page => params[:page], :per_page => 11)
    
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name,:name_cn, :level, :parent)
    end
end

app/assets/images/heli_admin/app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.number_field :parent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/assets/images/heli_admin/app/views/types/_san_pham.html.erb
<div class="box_sp">
  <a href="#">
    <%= link_to image_tag(san_pham.image_url), san_pham %>
  </a>
  <div class="box_namesp">
    <a><%= link_to san_pham.ten, san_pham %></a>
  </div>
  <div class="box_addsp">
    <%= t("home.lien_he") %>: 0969.042.725
  </div>
  <%= link_to t("san_pham.chi_tiet"), san_pham, :class => "tuychon" %>
</div>

app/assets/images/heli_admin/app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/assets/images/heli_admin/app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Level</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.id %></td>
        <td><%= type.name %></td>
        <td><%= type.level %></td>
        <td><%= type.parent %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/assets/images/heli_admin/app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/assets/images/heli_admin/app/views/types/show.html.erb
<% tmp=0%>
<% @san_phams.each do |san_pham| %>
<% if san_pham.type_id > tmp %>
<div class="classify_sp">
  <%= image_tag("image/forklift.png") %>
  <div class="classify_sp_heading">
    <% if san_pham.type_id == 2 %>
    <%= t("loai_xe.h2000") %>
    <% tmp =2 %>
    <% elsif san_pham.type_id == 3 %>
    <%= t("loai_xe.kseries") %>
    <% tmp = 3%>
    <% elsif san_pham.type_id == 4 %>
    <%= t("loai_xe.gseries") %>
    <% tmp = 4%>
    <% elsif san_pham.type.id == 5 %>
    <%= t("loai_xe.hseries") %>
    <% tmp = 5%>
    <% elsif san_pham.type_id == 7 %>
    <%= t("loai_xe.ac4banh") %>
    <% tmp = 7%>
    <% elsif san_pham.type_id == 8 %>
    <%= t("loai_xe.3banh") %>
    <% tmp = 8%>
    <% elsif san_pham.type_id == 9 %>
    <%= t("loai_xe.xe_nang_gas") %>
    <% tmp = 9%>
    <% elsif san_pham.type_id == 10 %>
    <%= t("loai_xe.xe_nang_reach_truck") %>
    <% tmp = 10%>
    <% elsif san_pham.type_id == 11 %>
    <%= t("loai_xe.xe_nang_xep_pallet") %>
    <% tmp = 11%>
    <% elsif san_pham.type_id == 12 %>
    <%= t("loai_xe.xe_nang_trong_tai_lon") %>
    <% tmp = 12%>
    <% elsif san_pham.type_id == 13 %>
    <%= t("loai_xe.xe_nang_container") %>
    <% tmp = 13%>
    <% end %>
  </div>
</div>
<% end %>
<%= render san_pham %>
<% end %>
<div class="pagination_center">
  <%= will_paginate @san_phams,renderer: BootstrapPagination::Rails %>
</div>