app/assets/images/heli_admin/config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /vi/ do
    root "static_pages#home"
    
    resources :types
    resources :san_phams
    resources :tin_tucs
    devise_for :users, :skip => [:sessions]
      as :user do
      get 'admin/login' => 'devise/sessions#new', :as => :new_user_session
      post 'admin/login' => 'devise/sessions#create', :as => :user_session
      match 'admin/signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    end
  end

end

app/assets/images/heli_admin/app/models/tin_tuc.rb
class TinTuc < ActiveRecord::Base
  mount_uploader :anh_tieu_de, ImageUploader
end

app/assets/images/heli_admin/app/controllers/tin_tucs_controller.rb
class TinTucsController < ApplicationController
  before_action :set_tin_tuc, only: [:show, :edit, :update, :destroy]

  # GET /tin_tucs
  # GET /tin_tucs.json
  def index
    @tin_tucs = TinTuc.all
  end

  # GET /tin_tucs/1
  # GET /tin_tucs/1.json
  def show
  end

  # GET /tin_tucs/new
  def new
    @tin_tuc = TinTuc.new
  end

  # GET /tin_tucs/1/edit
  def edit
  end

  # POST /tin_tucs
  # POST /tin_tucs.json
  def create
    @tin_tuc = TinTuc.new(tin_tuc_params)

    respond_to do |format|
      if @tin_tuc.save
        format.html { redirect_to tin_tucs_path, notice: 'Tạo tin mới thành công' }
        format.json { render :index, status: :created, location: tin_tucs }
      else
        format.html { render :new }
        format.json { render json: @tin_tuc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tin_tucs/1
  # PATCH/PUT /tin_tucs/1.json
  def update
    respond_to do |format|
      if @tin_tuc.update(tin_tuc_params)
        format.html { redirect_to tin_tucs_path, notice: 'Chỉnh sửa thông tin thành công' }
        format.json { render :index, status: :ok, location: tin_tucs }
      else
        format.html { render :edit }
        format.json { render json: @tin_tuc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tin_tucs/1
  # DELETE /tin_tucs/1.json
  def destroy
    @tin_tuc.destroy
    respond_to do |format|
      format.html { redirect_to tin_tucs_url, notice: 'Tin tuc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tin_tuc
      @tin_tuc = TinTuc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tin_tuc_params
      params.require(:tin_tuc).permit(:tieu_de, :anh_tieu_de, :noi_dung)
    end
end

app/assets/images/heli_admin/app/views/tin_tucs/_form.html.erb
<%= form_for(@tin_tuc) do |f| %>
  <% if @tin_tuc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tin_tuc.errors.count, "error") %> prohibited this tin_tuc from being saved:</h2>

      <ul>
      <% @tin_tuc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "Tiêu đề" %><br>
    <%= f.text_field :tieu_de %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Ảnh tiêu đề" %><br>
    <%= image_tag(@tin_tuc.anh_tieu_de.url, width: '200px', height: '200px') if @tin_tuc.anh_tieu_de? %>
    <%= f.file_field :anh_tieu_de %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Nội dung" %><br>
    <%= f.text_area :noi_dung, class: "ckeditor" %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  <br>
  <br>
<% end %>

app/assets/images/heli_admin/app/views/tin_tucs/edit.html.erb
<h1>Editing Tin Tuc</h1>

<%= render 'form' %>

<%= link_to 'Show', @tin_tuc %> |
<%= link_to 'Back', tin_tucs_path %>

app/assets/images/heli_admin/app/views/tin_tucs/index.html.erb
<div class="row">
        <div class="col-sm-12">
            <h1>
                <p>Tin tức</p>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h3> <span>Danh sách tin tức cũ</span></h3>
            <br>
            <table class="table table-bordered" >
                <tr>
                    <td class="tt_img">
                        <span class="title2">Ảnh đại diện</span>
                    </td>
                    <td class="tt_td">
                        <span class="title2">Tiêu đề</span>
                    </td>
                    <td class="tt_day">
                        <span class="title2">Ngày tạo</span>
                    </td>
                    <td class="tt_edit">
                        <span class="title2">Sửa</span>
                    </td>
                    <td  class="tt_edit">
                        <span class="title2">Xóa</span>
                    </td>
                </tr>
                <% @tin_tucs.each do |tin_tuc| %>

                <tr>
                    <td class="tt_img">
                      <%= image_tag(tin_tuc.anh_tieu_de.url, class: "img_tt")%>
                    </td>
                    <td>
                        <span><%= tin_tuc.tieu_de%></span>
                    </td>
                    <td class="tt_day">
                        <span><%= tin_tuc.created_at %></span>
                    </td>
                    <td class="tt_edit">
                        <a href="#"> <span><%= link_to "sửa", edit_tin_tuc_path(tin_tuc)%></span></a>
                    </td>
                    <td class="tt_edit">
                        <a href="#"> <span><%= link_to 'Xóa', tin_tuc, method: :delete, data: { confirm: 'Xóa tin tức này?'}%>
</span></a>
                    </td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>

app/assets/images/heli_admin/app/views/tin_tucs/new.html.erb
<div class="row">
        <div class="col-sm-12">
            <h1>
                <p>Thêm tin tức</p>
            </h1>
        </div>
    </div>
<%= render 'form' %>

app/assets/images/heli_admin/app/views/tin_tucs/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
<!--  <strong>Tieu de:</strong>-->
<!--  <%= @tin_tuc.tieu_de %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Anh tieu de:</strong>-->
<!--  <%= image_tag(@tin_tuc.anh_tieu_de.url, width: '200px', height: '200px') if @tin_tuc.anh_tieu_de? %>-->
<!--</p>-->
<div class="classify_sp">
  <div class="classify_sp_heading">
    TIN TỨC
  </div>
</div>
  <div class="title_gt">
  <div class="tieu_de'"><%= @tin_tuc.tieu_de %></div>
  <%= raw(@tin_tuc.noi_dung) %>
  </div>