app/assets/images/heli_admin/config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /vi/ do
    root "static_pages#home"
    
    resources :types
    resources :san_phams
    resources :tin_tucs
    devise_for :users, :skip => [:sessions]
      as :user do
      get 'admin/login' => 'devise/sessions#new', :as => :new_user_session
      post 'admin/login' => 'devise/sessions#create', :as => :user_session
      match 'admin/signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
    end
  end

end

app/assets/images/heli_admin/app/views/layouts/_header.html.erb
<header>
<nav class=" navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: "navbar-brand title_text" do %>
                    <i class="glyphicon glyphicon-home"></i>
                    Trang quản trị
            <% end %>
        </div>
        <div id="navbar" class="collapse navbar-collapse ">
            <ul class="nav navbar-nav">
                <li>
                  <%= link_to san_phams_path, class: "title_text" do %>
                    <i class="glyphicon glyphicon-tree-conifer"></i>
                    Sản phẩm 
                  <% end %>
                </li>
                <li><%= link_to tin_tucs_path, class: "title_text" do %>
                    <i class="glyphicon glyphicon-globe"></i>
                    Tin tức 
                  <% end %>
                </li>
                <li>
                  <%= link_to new_san_pham_path, class: "title_text" do %>
                    <i class="glyphicon glyphicon-save"></i>
                    Thêm xe
                  <% end %>
                </li>
                <li>
                  <%= link_to new_tin_tuc_path, class: "title_text" do %>
                    <i class="glyphicon glyphicon-save"></i>
                    Thêm tin tức
                  <% end %>
                </li>
                <% if user_signed_in? %>
                  <li><%= link_to "Thoát", destroy_user_session_path,method: :delete, class: "title_text exit"%></li>
                <% end %>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
</header>

app/assets/images/heli_admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeliAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

</head>
<body>
  <% if user_signed_in? %>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "thong-bao alert alert-#{message_type}") %>
    <% end %>
  <% end %>
    <%= yield %>
  </div>
  
</body>
</html>