config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /vi|cn/ do
    resources :san_phams do
      collection do
        get 'search_result'
      end
    end
    resources :types
    root 'san_phams#index'
    get 'static_pages/phu_tung'
    get 'static_pages/gmap'
    get 'static_pages/gioi_thieu'
    get 'static_pages/dich_vu_ki_thuat'
    get 'static_pages/bo_cong_tac'
    resources :tin_tucs
    match '/contacts', to: 'contacts#new', via: 'get'
    resources "contacts", only: [:new, :create]
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,        :validate => true
  attribute :phone_number,:validate => true
  attribute :address     
  attribute :email,       :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  
  validates :phone_number, :presence => true,
                          :numericality => true,
                          :length => { :minimum => 10, :maximum => 15 }
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Heli Viet Nam",
      :to => "quylong.bm@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/san_pham.rb
class SanPham < ActiveRecord::Base
	
  belongs_to :type
  
  mount_uploader :image, ImageUploader
  def self.search(search)
    if search
      where('ten LIKE ? or ten_cn LIKE ?', "%#{search}%", "%#{search}%")
    # else
    #   find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale
  def default_url_options(options = {})
      { locale: I18n.locale }.merge options
  end
  private
    def set_locale
     I18n.locale = params[:locale] || I18n.default_locale
     Rails.application.routes.default_url_options[:locale]= I18n.locale 
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if verify_recaptcha(model: @user) && @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/san_phams_controller.rb
class SanPhamsController < ApplicationController
  before_action :set_san_pham, only: [:show]

  # GET /san_phams
  # GET /san_phams.json
  def index
    @diesel = SanPham.where('type_id = 2 and tai_trong_nang = 2500')+SanPham.where('type_id = 2 and tai_trong_nang = 3500') + SanPham.where(:type_id => "3").limit(2) + SanPham.where('type_id = 4 and tai_trong_nang = 7000').limit(1) + SanPham.where('type_id = 5').limit(1)
    @dien = SanPham.where(:type_id => "7").limit(3) + SanPham.where(:type_id => "8").limit(3)
    @pallet = SanPham.where(:type_id => "11").limit(3)
    @other = SanPham.where(:type_id => "9").limit(2) + SanPham.where(:type_id => "10").limit(2) + SanPham.where(:type_id => "12").limit(1) + SanPham.where(:id => "13").limit(1)
  end
  def search_result
    @san_phams = SanPham.search(params[:search]).paginate(:page => params[:page], :per_page => 11)
  end
  # GET /san_phams/1
  # GET /san_phams/1.json
  def show
    @others = SanPham.where('type_id = ? and id != ?', @san_pham.type_id, @san_pham.id).order('cast(tai_trong_nang as unsigned) asc')
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_san_pham
      @san_pham = SanPham.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def san_pham_params
      params.require(:san_pham).permit(:type_id,:ten, :nha_san_xuat, :model, :kieu_dong_co, :kieu_hoat_dong, :so_di_chuyen, :tai_trong_nang, :tam_tai_trong, :loai_lop, :so_banh_xe_truoc_sau, :chieu_cao_nang_lon_nhat, :chieu_cao_nang_tu_do, :chieu_cao_khung_nang, :chieu_cao_co_so, :chieu_dai_co_so_voi_cang_nang, :chieu_dai_co_so, :chieu_rong_co_so, :khoang_cach_truc_banh_xe, :khoang_sang_gam_xe, :ban_kinh_vong_quay, :ban_kinh_vong_quay_nho_nhat, :goc_nghieng_cot_nang, :kich_thuoc_cang_nang_dai_rong_day, :toc_do_di_chuyen_lon_nhat_co_tai_va_khong_tai, :toc_do_nang_co_tai_va_khong_tai, :toc_do_ha_co_tai_va_khong_tai, :kha_nang_leo_doc_co_tai_va_khong_tai, :dien_nang_su_dung, :co_lop_truoc, :co_lop_sau, :tu_trong, :model_dong_co, :cong_suat_vong_quay, :dung_tich_buong_dot, :binh_chua_nhien_lieu, :mo_to_di_chuyen, :mo_to_bom, :he_thong_dieu_khien_mo_to_di_chuyen, :he_thong_dieu_khien_motor_bom, :he_thong_phanh, :ap_saut_dau_dinh_muc,:image,:ten_cn,:so_bac,:chieu_cao_cabin,:chieu_cao_khung_nang_khi_nang_cao_nhat,:khoang_dich_chuyen_cang,:luc_keo,:momen,:mo_to_lai,:mo_to_nang,:ac_quy,:chieu_cao_nang_tieu_chuan,:loai_dieu_khien_lai,:tong_khoi_luong)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
  def phu_tung
  end
  def gmap
  end
  def gioi_thieu
  end
  def dich_vu_ki_thuat
  end
  def bo_cong_tac
  end
end

app/controllers/tin_tucs_controller.rb
class TinTucsController < ApplicationController
  before_action :set_tin_tuc, only: [:show]

  def show
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tin_tuc
      @tin_tuc = TinTuc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tin_tuc_params
      params.require(:tin_tuc).permit(:tieu_de, :anh_tieu_de, :noi_dung)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end
  # GET /types/1
  # GET /types/1.json
  def show
    @type_childs = Type.where(:parent => @type.id)
    @type_child_ids = [@type.id]
    @type_childs.each do |type_child|
      @type_child_ids.push(type_child.id)
    end
    @san_phams = SanPham.where(:type_id => @type_child_ids).order('type_id asc').paginate(:page => params[:page], :per_page => 11)
    
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name,:name_cn, :level, :parent)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def san_pham_ban_chay
    san_pham_ban_chay = SanPham.where(:type_id => 2, :tai_trong_nang => "3000") + SanPham.where(:type_id => 3, :tai_trong_nang => "3000") + SanPham.where(:type_id => 2, :tai_trong_nang => "5000") + SanPham.where(:type_id => 7, :tai_trong_nang => "2000")
  end
  def tin_tuc_moi
    tin_tuc_moi = TinTuc.all.order(:created_at).limit(4)
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="title_gt">
            <p class="title_bold">
                GỬI THÔNG TIN YÊU CẦU TRỰC TUYẾN
            </p>
            <br>
            <p>
                Các yêu cầu sẽ được chuyển tới <span class="title_bold">CÔNG TY TNHH XE NÂNG BÌNH MINH</span>, chúng tôi sẽ trả lời trong thời gian sớm nhất có thể
            </p>
            <br>
            <div class="title_center">
                <p> Copyright © 2015 - <span class="title_bold">Heli Forklift</span></p>
                <p class="title_bold">Công ty TNHH xe nâng Bình Minh</p>
                <p class="title_bold">Trụ sở chính :Km 9+500, Nguyễn Văn Linh,Sài Đồng,Long BIên,Hà Nội</p>
                <p class="title_bold">Chi nhánh TP HCM: 288/2 QL1A, P.Thới An, Q12, TP Hồ Chí Minh</p>
                <p class="title_bold">Hotline: 0969 042 725- Mr.Long</p>
                <p class="title_bold">Email: quylong.bm@gmail.com  - Website: helivietnam.org</p>
                <%= simple_form_for @contact do |f| %>

                <table class="tintin_table" >
                    <tr>
                        <td class="category_tt">
                            <span>Name:</span>
                        </td>
                        <td class="category_tt2">
                            <%= f.input :name,:label => false, :required => true, :input_html =>{class: "input_lien_he"} %>
                            <span>(<span class="big_tt">*</span>)</span>

                        </td>
                    </tr>
                    <tr>
                        <td class="category_tt">
                            <span>Phone number:</span>
                        </td>
                        <td class="category_tt2">
                            <%= f.input :phone_number,:label => false, :required => true, :input_html =>{class: "input_lien_he"} %>
                            <span>(<span class="big_tt">*</span>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="category_tt">
                            <span>Address:</span>
                        </td>
                        <td class="category_tt2">
                            <%= f.input :address,:label => false, :input_html =>{class: "input_lien_he"} %>
                        </td>
                    </tr>
                    <tr>
                        <td class="category_tt">
                            <span>Email:</span>
                        </td>
                        <td class="category_tt2">
                            <%= f.input :email,:label => false, :required => true, :input_html =>{class: "input_lien_he"} %>
                            <span>(<span class="big_tt">*</span>)</span>
                        </td>
                    </tr>
                    <tr>
                        <td class="category_tt">
                            <span>Message:</span>
                        </td>
                        <td class="category_tt2">
                            <%= f.input :message,:label => false, :as => :text, cols: "3", role: "10", :required => true, :input_html => {class: "textarea"} %>
                        </td>
                        
                    </tr>
                    <tr>
                      <td></td>
                      <td> <%= recaptcha_tags %></td>
                    </tr>
                    <br>
                    <tr>
                        <td class="category_tt">
                        </td>
                        <td class="category_tt2">
                            <%= f.button :submit, 'Send message', :class=> "btn btn-primary submit_bt" %>
                        </td>
                    </tr>
                </table>
                <% end %>
            </div>

        </div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="footer-wrap">
        <div class="footer-left">
            <%= image_tag("logo/bm.png",:class => "logo_bm")%>
            <p class="footer-links">
                <%= link_to t("home.trang_chu2"), root_path%>
                ·
                <%= link_to t("home.gioi_thieu2"), root_path%>
                ·
                <%= link_to t("home.dich_vu_ki_thuat2"), root_path%>
                ·
                <%= link_to t("home.phu_tung2"), static_pages_phu_tung_path%>
                ·
                <%= link_to t("home.ban_do2"), static_pages_gmap_path%>
                ·
                <%= link_to t("home.lien_he2"), contacts_path%>
            </p>
            <p class="footer-company-name">Xe Nâng Binh Minh &copy; 2015</p>
        </div>
        <div class="footer-center">
                <table>
                    <tr>
                        <td>
                <i class="fa fa-map-marker"></i>
                        </td>
                        <td>
                <p><span>Km 9+500, Nguyễn Văn Linh,Sài Đồng,Long BIên,Hà Nội
                    <br>
                        CNMN : 288/2 QL1A, P.Thới An, Q12, TP Hồ Chí Minh</span></p>
                        </td>
                    </tr>
                    <tr>
                        <td>

                <i class="fa fa-phone"></i>
                        </td>
                        <td>
                <p>Mr Long: 0969.042.725 </p>

                        </td>
                    </tr>
                    <tr>
                        <td>

                <i class="fa fa-envelope"></i>
                        </td>
                        <td>
                <p class="mail_footer">quylong.bm@gmail.com</p>
                        </td>
                    </tr>
                    <tr>
                        <td>

                            <i class="fa fa-facebook"></i>
                        </td>
                        <td>
                            <iframe src="//www.facebook.com/plugins/follow?href=https%3A%2F%2Fwww.facebook.com%2Fheli.vietnam&amp;layout=standard&amp;show_faces=true&amp;colorscheme=light&amp;width=450&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
                        </td>
                    </tr>
                </table>
        </div>
        <div class="footer-right">
            <%= image_tag("logo/logo_footer.png",:class => "logo_right")%>
        </div>
    </div>
 
</div>

app/views/layouts/_header.html.erb
    <header>
        <div class="top-header clearfix">
            <div class="logo">

              <a href="#">
                <%= link_to image_tag("logo/logo.png"),root_path %>
              </a>
            </div>
            <div class="phone_blink">
                <span class="hotline"> <%= t("home.hotline")%>:</span>
                <span class="blink_me">0969 042 725</span>
            </div>
            <div class="flag_lang">
                <%= link_to image_tag("image/cn.png",:class => "china flag"), "/cn/", :class => "lang_flag"%>
                <%= link_to image_tag("image/vn.png", :class => "vietnam flag"), "/vi/", :class => "lag_flag"%>
                
            </div>
        </div>
        
        <section class="slider">
            <div class="banner">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                              <%= image_tag("slider/1.jpg")%>
                            </div>
                            <div class="item">
                              <%= image_tag("slider/2.jpg")%>
                            </div>
                            <div class="item">
                              <%= image_tag("slider/3.jpg")%>
                            </div>
                            <div class="item">
                              <%= image_tag("slider/4.jpg")%>
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
            </div>
        </section>
        <div class="banner-menu">
        <div id="cssmenu" >
                    <ul id="nav">
                        <li class = "z115"><%= link_to t("home.trang_chu"), root_path %></li>
                        <li class = "z100"><%= link_to t("home.gioi_thieu"), static_pages_gioi_thieu_path %></li>
                        <li class = "z125">
                            <%= link_to root_path do %>
                              <span ><%=t("home.san_pham") %></span>

                              <span class="caret"></span>
                            <% end %>
                            <ul >
                              <% @types = Type.menu_level_1 %>
                              <% @types.each do |type| %>
                                <li>
                                  <%= link_to type do%>
                                    
                                    <% if type.id == 1 %>
                                    <%= link_to  type do%>
                        <%=  image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_hang_diesel_heli") %>
                      <% end %>
                    <% elsif type.id == 6 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_dien_heli") %>
                      <% end %>
                    <% elsif type.id == 9 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_gas") %>
                      <% end %>
                    <% elsif type.id == 10 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_reach_truck") %>
                      <% end %>
                    <% elsif type.id == 11 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_xep_pallet") %>
                      <% end %>
                    <% elsif type.id == 12 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_trong_tai_lon") %>
                      <% end %> 
                    <% elsif type.id == 13 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_container") %>
                      <% end %>
                                  <% end %>
                                  <% end %>
                                </li>    
                              <% end %>
                            </ul>
                        </li>
                        <li class = "z155"><%= link_to t("home.dich_vu_ki_thuat"), static_pages_dich_vu_ki_thuat_path %></li>
                        <li class = "z110"><%= link_to t("home.phu_tung"), static_pages_phu_tung_path %></li>
                        <li class = "z95"><%= link_to t("home.ban_do"), static_pages_gmap_path %></li>
                        <li class = "z95"><%= link_to t("home.lien_he"), contacts_path %></li>

                     </ul>
                    <%= form_tag search_result_san_phams_path,{:method => 'get', :class => "navbar-form navbar-left"} do %>
                        <%= text_field_tag :search, params[:search],class: "form-control", :placeholder => t("home.search") %>
                        <%= button_tag(type: "submit", class: "btn btn-default glyphicon glyphicon-search") do %>
                        <% end %>
                    <% end %>
                   
        </div>
        </div>
    </header>
    

app/views/layouts/_list_form.html.erb
<div class="classify_sp">
  <div class="classify_sp_heading"> Xe nâng Diesel Heli
  </div>
</div>
<div class="box_sp">
  <a href="#">
    <img src="img/image/image_1392255979.jpg">
  </a>
  <div class="box_namesp">
    <a>Xe nâng Diesel Heli CPCD20- 2 tấn</a>
  </div>
  <div class="box_addsp">
    Liên hệ: 0969. 0427. 25
  </div>
  <a class="tuychon" href="#">CHI TIẾT</a>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_slide_left.html.erb
<div class="container-left clearfix">
        <div id="menu_content">
            <h3 class="menu_content_header"><%= t("loai_xe.xe_nang_hang")%></h3>
            <ul>
                <% @types = Type.menu_level_1 %>
                <% @types.each do |type| %>
                  <li>
                    <% if type.id == 1 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_hang_diesel_heli") %>
                      <% end %>
                    <% elsif type.id == 6 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_dien_heli") %>
                      <% end %>
                    <% elsif type.id == 9 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_gas") %>
                      <% end %>
                    <% elsif type.id == 10 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_reach_truck") %>
                      <% end %>
                    <% elsif type.id == 11 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_xep_pallet") %>
                      <% end %>
                    <% elsif type.id == 12 %>
                      <%= link_to type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_trong_tai_lon") %>
                      <% end %> 
                    <% elsif type.id == 13 %>
                      <%= link_to  type do%>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("loai_xe.xe_nang_container") %>
                      <% end %>
                    <% end %>
                    <ul class="sub-menu_content">
                        <% @type_childs = Type.menu_level_2(type)%>
                        <% @type_childs.each do |type_child| %>
                          <li>
                            <% if type_child.id == 2 %>
                              <%= link_to t("loai_xe.h2000"), type_child %>
                            <% elsif type_child.id == 3 %>
                              <%= link_to t("loai_xe.kseries"), type_child %>
                            <% elsif type_child.id == 4 %>
                              <%= link_to t("loai_xe.gseries"), type_child %>
                            <% elsif type_child.id == 5 %>
                              <%= link_to t("loai_xe.hseries"), type_child %>
                            <% elsif type_child.id == 7 %>
                              <%= link_to t("loai_xe.ac4banh"), type_child %>
                            <% elsif type_child.id == 8 %>
                              <%= link_to t("loai_xe.3banh"), type_child %>
                            <% end %>
                          </li>
                        <% end %>
                    </ul>
                  </li>    
                <% end %>
                <li><%= link_to static_pages_bo_cong_tac_path do %>
                        <%= image_tag("image/1247-200.png", :class => "forklift") %>
                        <%= t("menu_left.lua_chon_bo_cong_tac") %>
                      <% end %></li>
            </ul>
        </div>
        <%= image_tag("logo/bong_menu.png")%>
         <div class="support-content ">
             <h3 class="menu_content_header"><%= t("menu_left.ho_tro_truc_tuyen")%></h3>
             <table class="table-suport">
                 <tr>
                     <td align="center">
                         <strong>
                            <span>
                                <%= t("menu_left.kinh_doanh") %>
                            </span>
                         </strong>
                         <br>
                        <span class="phone_content">
                                0969042725
                        </span>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <%= image_tag("logo/online.gif")%>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <span class="mail_content">quylong.bm@gmail.com </span>
                     </td>
                 </tr>
                 <tr>
                     <td align="center">
                         <strong>
                            <span>
                                <%= t("menu_left.ho_tro_ky_thuat") %>
                            </span>
                         </strong>
                         <br>
                        <span  class="phone_content">
                                01665387186
                        </span>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <%= image_tag("logo/online.gif")%>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <span class="mail_content">quylong.bm@gmail.com </span>
                     </td>
                 </tr>
             </table>
         </div>
         <%= image_tag("logo/bong_menu.png")%>
         <div class="statistic-content ">
             <h3 class="menu_content_header"><%= t("menu_left.thong_ke_truy_cap") %></h3>
             <table cellspacing="0" cellpadding="0" border="0">
                 <tr>
                     <td>
                         <span class="glyphicon glyphicon-user"></span>
                         <span> <%= t("menu_left.dang_truy_cap")%>:</span>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <span class="glyphicon glyphicon-home"></span>
                         <span><%= t("menu_left.hom_nay") %>:</span>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <span class="glyphicon glyphicon-calendar"></span>
                         <span><%= t("menu_left.thang_hien_tai") %>:</span>
                     </td>
                 </tr>
                 <tr>
                     <td>
                         <span class="glyphicon glyphicon-stats"></span>
                         <span><%= t("menu_left.tong_so_luot_truy_cap") %>:</span>
                     </td>
                 </tr>
                
             </table>
         </div>
         <%= image_tag("logo/bong_menu.png")%>
    </div>

app/views/layouts/_slide_right.html.erb
<div class="container-right ">
  <div class="new-content ">
    <h3 class="menu_content_header"><%= t("menu_right.tin_moi") %></h3>
    <marquee direction="up" scrollamount="3" onmouseover="this.stop()" onmouseout="this.start()">
      <ul>
        <% tin_tuc_moi.each do |tin_tuc|%>
        <li>
          <%= link_to image_tag("heli_admin/public"+tin_tuc.anh_tieu_de.url), tin_tuc %>
          <%= link_to tin_tuc.tieu_de, tin_tuc %>
        </li>
        <% end %>
      </ul>
    </marquee>
  </div>
  <%= image_tag('logo/bong_menu.png')%>
  <div class="container-right-video ">
    <h3 class="menu_content_header"><%= t("menu_right.video") %></h3>
    <div class="video_content">
            <a href="https://www.youtube.com/embed/A7kkySr12LI" rel="shadowbox;width=640;height=385">
              <%= image_tag("logo/image_1391315542.jpg", :width => "185", :height => "131")%>
            </a>
            </div>
            <a href="https://www.youtube.com/embed/sXnNAvkZxCg" rel="shadowbox;width=640;height=385">
            <span class="support_video video-link2 demo-link" >(<%= t("menu_right.xem_them_video")%>)</span>
            </a>
  </div>
  <%= image_tag('logo/bong_menu.png')%>
  <div class="hot_sp " >
    <h3 class="menu_content_header"><%= t("menu_right.san_pham_ban_chay") %></h3>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <ul>
      <% san_pham_ban_chay.each do |san_pham|%>
      <li>
        <%= link_to image_tag("heli_admin/public"+san_pham.image_url), san_pham%>
        <br>
        <strong><% if t("language") == "cn" %>
            <%= link_to san_pham.ten_cn, san_pham %>
          <% elsif %>
            <%= link_to san_pham.ten, san_pham %>    
          <% end %></strong>
        <br>
        <strong class="denwa"><%= t("san_pham.lien_he")%>: 0969.042.725 </strong>
  
      </li>
      <% end %>
    </ul>
  </div>
  <%= image_tag("logo/bong_menu.png")%>
</div>

app/views/static_pages/home.html.erb
<p>Hello</p>